// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web uses the same JS-SDK config as Windows
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAhvO3a3xvrdCoqAFU8rgGQedRBmPZWHc',
    appId: '1:360739375700:web:9ffc681c2a5615771b3bc1',
    messagingSenderId: '360739375700',
    projectId: 'jeevamitra',
    authDomain: 'jeevamitra.firebaseapp.com',
    storageBucket: 'jeevamitra.firebasestorage.app',
    measurementId: 'G-PFYJTP6936',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jfwTsvShnTXIsY5d6BtQdQWNZnjNRNA',
    appId: '1:360739375700:android:3bddc2ca498360b41b3bc1',
    messagingSenderId: '360739375700',
    projectId: 'jeevamitra',
    storageBucket: 'jeevamitra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkrtuMrnwb5xl8yVMi7To1Z39gKWAluI',
    appId: '1:360739375700:ios:a5e1ec8834b178621b3bc1',
    messagingSenderId: '360739375700',
    projectId: 'jeevamitra',
    storageBucket: 'jeevamitra.firebasestorage.app',
    iosBundleId: 'com.jeevamitra.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAhvO3a3xvrdCoqAFU8rgGQedRBmPZWHc',
    appId: '1:360739375700:web:9ffc681c2a5615771b3bc1',
    messagingSenderId: '360739375700',
    projectId: 'jeevamitra',
    authDomain: 'jeevamitra.firebaseapp.com',
    storageBucket: 'jeevamitra.firebasestorage.app',
    measurementId: 'G-PFYJTP6936',
  );
}
