// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jfwTsvShnTXIsY5d6BtQdQWNZnjNRNA',
    appId: '1:360739375700:android:3bddc2ca498360b41b3bc1',
    messagingSenderId: '360739375700',
    projectId: 'jeevamitra',
    storageBucket: 'jeevamitra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkrtuMrnwb5xl8yVMi7To1Z39gKWAluI',
    appId: '1:360739375700:ios:a5e1ec8834b178621b3bc1',
    messagingSenderId: '360739375700',
    projectId: 'jeevamitra',
    storageBucket: 'jeevamitra.firebasestorage.app',
    iosBundleId: 'com.pasumitra.pasumitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAhvO3a3xvrdCoqAFU8rgGQedRBmPZWHc',
    appId: '1:360739375700:web:9ffc681c2a5615771b3bc1',
    messagingSenderId: '360739375700',
    projectId: 'jeevamitra',
    authDomain: 'jeevamitra.firebaseapp.com',
    storageBucket: 'jeevamitra.firebasestorage.app',
    measurementId: 'G-PFYJTP6936',
  );
}
